package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Publish'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Publish")) {
    vcs {
        add(DslContext.settingsRoot.id!!)
    }
}
