package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.GradleBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Publish'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Publish")) {
    expectSteps {
        gradle {

            conditions {
                doesNotExist("env.ARTIFACT_VERSION")
                doesNotExist("env.ARTIFACT_BUILD_ID")
            }
            tasks = ":find-latest-version:run"
        }
        gradle {
            tasks = ":repackage-and-publish:checkAlreadyPublished"
        }
        gradle {

            conditions {
                doesNotEqual("alreadyPublished", "true")
            }
            tasks = ":repackage-and-publish:publish"
        }
    }
    steps {
        update<GradleBuildStep>(0) {
            clearConditions()

            conditions {
                doesNotExist("env.ARTIFACT_VERSION")
                doesNotExist("env.ARTIFACT_BUILD_ID")
            }
            jdkHome = "%env.JDK_17_0_x64%"
        }
        update<GradleBuildStep>(1) {
            clearConditions()
            jdkHome = "%env.JDK_17_0_x64%"
        }
    }
}
