package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.triggers.ScheduleTrigger
import jetbrains.buildServer.configs.kotlin.triggers.schedule
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Publish'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Publish")) {
    triggers {
        val trigger1 = find<ScheduleTrigger> {
            schedule {
                schedulingPolicy = cron {
                    seconds = "0"
                    minutes = "0"
                    hours = "*/3"
                    dayOfMonth = "?"
                    dayOfWeek = "*"
                    month = "*"
                    year = "*"
                }
                triggerBuild = always()
                withPendingChangesOnly = false
            }
        }
        trigger1.apply {
            enabled = false

        }
    }
}
